# Generated by Django 5.0 on 2023-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='currency',
            field=models.CharField(choices=[('KZT', 'KZT'), ('USD', 'USD'), ('EUR', 'EUR')], default='KZT', max_length=3),
        ),
    ]
