# Generated by Django 5.0 on 2023-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_alter_accountholder_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='wallet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
    ]
